project:
  type: website
  output-dir: docs

website:
  title: "mattnkm"
  site-url: https://mattnkm.github.io
  description: MNG
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mattnkm
      - icon: google
        href: https://scholar.google.com/citations?user=4f8ZKfAAAAAJ
format:
  html:
    theme: sandstone
    css: styles.css
editor: visual

